# fly.toml app configuration file generated for black-grass-8530 on 2023-05-29T18:35:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-grass-8530"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
